.. include:: micro/object-attributes.inc

.. include:: micro/editable-attributes.inc

.. describe:: title

   Site title.

.. describe:: icon

   URL of the site icon. May be ``null``.

.. describe:: icon_small

   URL of the site icon optimized for small scale. Should be 16 pixels square. May be ``null``.

.. describe:: icon_large

   URL of the site icon optimized for large scale. Should be 512 pixels square. May be ``null``.

.. describe:: provider_name

   Service provider name. May be ``null``.

.. describe:: provider_url

   URL of the website of the service provider. May be ``null``.

.. describe:: provider_description

   Short polyglot description of the service provider, which can be read as an addendum to the
   *provider_name*.

.. describe:: feedback_url

   URL of the feedback site / help desk. May be ``null``.

.. describe:: staff

   Staff users.

.. describe:: push_vapid_public_key

   VAPID public key used for sending device notifications.
